

services:

   dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt_trans_snowflake
    ports:
      - "8087:8087"
    env_file:
      - ./dbt_project/dbt_meteo/models/.env
    volumes:
      - ./dbt_project:/usr/app
    working_dir: /usr/app
    tty: true
    stdin_open: true
    networks:
      - comores_meteo
      
